version: '3.9'
services:
  mysql:
      image: mysql/mysql-server:8.0
      container_name: mysql-inst
      restart: unless-stopped
      tty: true
      volumes:
        - ./db:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: mkt_data_db
        MYSQL_USER: mkt_data_usr
        MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql-inst
      secrets:
        - db_user_password
        - db_root_password
      networks:
        - app_network

networks:
  app_network:
    driver: bridge

secrets:
  db_user_password:
    file: ../secrets/db_user_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt